name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install root deps
        run: pnpm install
      - name: Install app deps
        run: pnpm -C app install
      - name: Create env for Vite from GitHub Secrets
        run: |
          echo "VITE_API_BASE=${{ secrets.VITE_API_BASE }}" >> app/.env
          echo "VITE_PUBLIC_SIGNING_SALT=${{ secrets.VITE_PUBLIC_SIGNING_SALT }}" >> app/.env
          echo "VITE_FB_API_KEY=${{ secrets.VITE_FB_API_KEY }}" >> app/.env
          echo "VITE_FB_AUTH_DOMAIN=${{ secrets.VITE_FB_AUTH_DOMAIN }}" >> app/.env
          echo "VITE_FB_PROJECT_ID=${{ secrets.VITE_FB_PROJECT_ID }}" >> app/.env
          echo "VITE_FB_STORAGE_BUCKET=${{ secrets.VITE_FB_STORAGE_BUCKET }}" >> app/.env
          echo "VITE_FB_MESSAGING_SENDER_ID=${{ secrets.VITE_FB_MESSAGING_SENDER_ID }}" >> app/.env
          echo "VITE_FB_APP_ID=${{ secrets.VITE_FB_APP_ID }}" >> app/.env
      - name: Build app
        run: pnpm -C app build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: app/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4